# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration
  # Orbs reduce the amount of configuration required for common tasks.
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
