# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration
  # Orbs reduce the amount of configuration required for common tasks.
  heroku: circleci/heroku@1.2.4

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main # only run deploy-via-git job on master branch
